apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: "external"
bootstrapTokens:
- token: "jz4v8t.r7j2asmt9vky557c"
  description: "kubeadm bootstrap token"
  ttl: "1h"
#- token: "v6tnhv.rxs8u4868se7r64r"
#  description: "tls bootstrap token"
#  usages:
#  - authentication
#  - signing
#  groups:
#  - system:bootstrappers:kubeadm:default-node-token
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: stable
#controlPlaneEndpoint: "LOAD_BALANCER_IP:6443"
networking:
  podSubnet: 10.244.0.0/16
controllerManager:
  extraArgs:
    "external-cloud-volume-plugin": "openstack"
  extraVolumes:
  - name: "cloud-config"
    hostPath: "/etc/kubernetes/cloud-config"
    mountPath: "/etc/kubernetes/cloud-config"
    readOnly: true
    pathType: FileOrCreate
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
#---
#apiVersion: kubeadm.k8s.io/v1beta2
#kind: JoinConfiguration
#discovery:
#  bootstrapToken:
#    apiServerEndpoint: LOAD_BALANCER_IP:6443
#    token: jz4v8t.r7j2asmt9vky557c
#    unsafeSkipCAVerification: true
#  timeout: 5m0s
#  tlsBootstrapToken: v6tnhv.rxs8u4868se7r64r